### ISSUE TITLE
Types incompatible with tailwind/nesting recommended config

### ISSUE THREAD

**Issue by jancbeck** [postcss/postcss-load-config#267]
Tailwind [docs describe using nesting](https://tailwindcss.com/docs/using-with-preprocessors#nesting) as follows: 

> Then pass the plugin itself as an argument to tailwindcss/nesting in your PostCSS configuration:
> ```
> // postcss.config.js
> module.exports = {
>   plugins: {
>     'postcss-import': {},
>     'tailwindcss/nesting': 'postcss-nesting',
>     tailwindcss: {},
>     autoprefixer: {},
>   }
> }
> ```

However, the types of **postcss-load-config** don't allow this because a record in the plugins property has to have a value of type `object | false` not `string`.

**Comment by ai** [comment]
Please send PR

**Comment by brc-dd** [comment]
I think the issue should be created with tailwindcss. We have checks like this:

https://github.com/postcss/postcss-load-config/blob/824a7de5f625310505504b2d79526ee8d608194f/src/plugins.js#L20

These aren't meant to handle string options. It doesn't break in runtime because we don't have a `typeof` check there and `Object.keys(str).length` is same as `str.length`, but IMO that's not an intended usage.

**Comment by jancbeck** [comment]
> IMO that's not an intended usage.

@brc-dd what's the intended usage in a scenario like mentioned in the TW docs?

**Comment by brc-dd** [comment]
Tailwind's plugin types and arguments are wrong.`options` in **postcss-load-config** was never meant to be a string. They made that argument a string in their function and that's why they need you to pass a string. But they do support the options format too. So you can do this if you worry about types:

```ts
'tailwindcss/nesting': require('postcss-nesting')
```

**Comment by jancbeck** [comment]
That works for me, thanks!
